# https://golangci-lint.run/usage/configuration/
run:
  timeout: 2m

output:
  format: tab

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - dupl
    - depguard
    - gocritic
    - gocyclo
    - gofmt
    - golint
    - misspell
    - unconvert

linters-settings:
  depguard:
    rules:
      prevent_unmaintained_packages:
        list-mode: lax # allow unless explicitely denied
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - 'github.com/clok'
          - 'github.com/urfave/cli/v2'
          - 'github.com/aws/aws-sdk-go'
          - 'github.com/jedib0t/go-pretty'
          - 'github.com/a8m/djson'
          - 'github.com/TylerBrock/colorjson'
          - 'github.com/AlecAivazis/survey/v2'
          - 'github.com/logrusorgru/aurora/v3'
